sudo: false
language: scala

# https://docs.travis-ci.com/user/notifications/#IRC-notification
notifications:
  irc:
    channels:
      - "chat.freenode.net#lichess"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    rooms:
      - lichess:sVTqlE0OQNMPq1n6qRnVnfrz
    on_success: change
    on_failure: always
  email: false

# https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
jdk:
  - oraclejdk8

env:
  global:
   - secure: "VkgJ78marLdG8JQrWV3UhcxXyWmdy6BV3gYLTyXpK2ltPA4vGkFilZDc8hMx2VhYeeTXyvXB+PM4xkB40PUnDlmNXIWQlG7IxKIb/zxwUVS+WcvAzM6yqEV9B/UbZO+Mgp2Hl4/F1lMoIpdQ0tkRvHmfw01L9VDrQs4Otdmd38o="
   - TRAVIS_NODE_VERSION="4.0.0"

install:
  # http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install "$TRAVIS_NODE_VERSION"
  - npm install -g gulp

  - git submodule update --init --recursive
  - ./ui/build
  - ./bin/build-deps.sh

script:
  - sbt compile
  - sbt test
