name: Lint code

on:
  push:
    branches-ignore:
      - 'l10n_master'
  pull_request:
    paths-ignore:
      - 'translation/dest/**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install && yarn run check-format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd ui && yarn install && yarn run lint
