name: Build server

on:
  push:
    paths:
    - '.github/workflows/server.yml'
    - 'app/**'
    - 'conf/**'
    - 'modules/**'
    - 'project/**'
    - 'translation/**'
    - 'build.sbt'
    - 'lila'
    - 'conf/application.conf.default'
    - '.sbtopts.default'
    branches-ignore:
    - 'l10n_master'
  pull_request:
    paths:
    - '.github/workflows/server.yml'
    - 'app/**'
    - 'conf/**'
    - 'modules/**'
    - 'project/**'
    - 'translation/source/**'
    - 'build.sbt'
    - 'lila'
    - 'conf/application.conf.default'
    - '.sbtopts.default'

jobs:
  openjdk13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "autoformat=false" > ~/.scalariform.conf
    - name: Work around OverlappingFileLockException
      run: mkdir -p ~/.sbt && sudo mount -t tmpfs -o size=1536m tmpfs ~/.sbt
    - uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-openjdk13-20200408-ivy2
    - uses: olafurpg/setup-scala@49fc8c734ef6916b4e1da8ba8d81bb26a2b46a06 # v7
      with:
        java-version: openjdk@1.13.0-2
    - run: TZ=UTC git log -1 --date=iso-strict-local --pretty='format:app.version = """%h / %ad / %s"""%n' | tee conf/version.conf
    - run: ./lila -Dsbt.boot.lock=false -Depoll=true "test;stage"
    - run: cp LICENSE COPYING.md README.md target/universal/stage && git log -n 1 --pretty=oneline > target/universal/stage/commit.txt
    - run: cd target/universal/stage && tar -cvpJf lila-3.0.tar.xz . && cd -
    - uses: actions/upload-artifact@v1
      with:
        name: lila-server
        path: lila-3.0.tar.xz
