name: Build server

on:
  push:
    paths:
    - 'app/**'
    - 'conf/**'
    - 'modules/**'
    - 'project/**'
    - 'build.sbt'
    branches-ignore:
    - 'l10n_master'
  pull_request:
    paths:
    - 'app/**'
    - 'conf/**'
    - 'modules/**'
    - 'project/**'
    - 'build.sbt'
    branches-ignore:
    - 'l10n_master'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: echo "autoformat=false" > ~/.scalariform.conf
    - run: mkdir -p target/universal/stage && cp LICENSE COPYING.md README.md target/universal/stage/ && git log -n 1 --pretty=oneline > target/universal/stage/commit.txt
    - uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy2
    - uses: olafurpg/setup-scala@v7
       with:
         java-version: openjdk@1.13
    - run: ./lila test:compile test stage
    - run: du -d2 -h ~
    - uses: actions/upload-artifact@v1
      with:
        name: lila-server
        path: target/universal/stage
